add setting to remove the background from chat, only when the chat is closed
Sk1erLLC/Patcher pull request #119
Opened 2022-10-06 15:02 UTC by Alexdoru

Tested, both working in 1.8.9 and 1.12.2

Closes https://github.com/Sk1erLLC/Patcher/issues/83

2022-11-12 02:33 UTC, Sychic requested changes

2022-11-12 02:33 UTC, Sychic commented on src/main/java/club/sk1er/patcher/mixins/features/GuiNewChatMixin_TransparentChat.java
> +    @SuppressWarnings("unused")
Not needed, the editor just doesn't recognize mixinextra annotations as mixin annotations yet.

2022-11-12 02:33 UTC, Sychic commented on src/main/java/club/sk1er/patcher/config/PatcherConfig.java
> +        description = "Remove the background from chat, only when the chat is closed.\n§eCan positively impact performance.",
```suggestion
        type = PropertyType.SWITCH, name = "Chat Background When Open",
        description = "Add back the background when chat is open.",
```
Though this wording is also a bit awkward.

2022-11-16 15:37 UTC, Sychic approved these changes

2022-11-16 22:28 UTC, DJtheRedstoner approved these changes

2022-11-16 22:29 UTC, merged