Begin converting all access transformers to Mixin accessors
Sk1erLLC/Patcher pull request #31
Opened 2021-10-09 19:13 UTC by ChachyDev

2021-10-09 19:15 UTC, asbyth commented on src/main/resources/patcher.mixins.json
> +    "accessors.BlockAccessor"
Shove this into the client array

2021-10-09 19:15 UTC, asbyth commented on src/main/resources/patcher_at.cfg
> +public net.minecraft.client.renderer.GlStateManager$Color
Move this above TextureState so the diff is more precise

2021-10-09 19:16 UTC, LlamaLad7 commented on src/main/resources/patcher.mixins.json
> +    "accessors.BlockAccessor"
MCDev moment

2021-10-09 20:53 UTC, LlamaLad7 approved these changes
Looks fine at a glance.

2021-10-10 03:41 UTC, asbyth requested changes

2021-10-10 03:41 UTC, asbyth commented on src/main/java/club/sk1er/patcher/hooks/MinecraftHook.java
> +public class    MinecraftHook {
Remove this random spacing

2021-10-10 03:41 UTC, asbyth commented on src/main/java/club/sk1er/patcher/hooks/ResourcePackRepositoryHook.java
> +    public static void updateRepositoryEntriesAll(ResourcePackRepository r) {
Rename this back to "repository" & make the variable accessor or something similar

2021-10-10 03:41 UTC, asbyth commented on src/main/resources/patcher_at.cfg
> +public net.minecraft.block.BlockRedstoneTorch$Toggle
Move this to the bottom & add it's comment back so the diff is more precise

2021-10-10 03:41 UTC, asbyth commented on src/main/resources/patcher_at.cfg
> +# net.minecraft.client.resources.ResourcePackRepository$Entry
Rename this to `ResourcePackRepository`

2021-10-10 03:41 UTC, asbyth commented on src/main/resources/patcher_at.cfg
> +# net.minecraft.client.renderer.tileentity.TileEntityBannerRenderer$TimedBannerTexture
Rename this to `TileEntityBannerRenderer`

2021-10-10 07:13 UTC, merged